---
- hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install deps packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      tags:
        - docker

    - name: GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: repository docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"
        state: present

    - name: install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes

    - name: Add remote "vagrant" user to "docker" group
      remote_user: vagrant
      user:
        name: "vagrant"
        group: "docker"
        append: yes
      tags:
        - docker
